name: Visit website every 2 seconds

on:
  push:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  visit-website:
    runs-on: ubuntu-latest
    steps:
    - name: HTTP request
      run: |
        for i in {1..1000}; do
          status=$(curl -s -o /dev/null -w '%{http_code}' http://example.com)
          echo "Visit $i returned status code: $status"
        done
