name: Process Content

on:
  push:
    branches:
      - main  # 可以指定触发工作流的分支
  schedule:
    - cron: '*/2 * * * *'  # 每 2 分钟触发一次（注意 GitHub Actions 的最小时间粒度为 1 分钟）

jobs:
  process-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4' # 你可以选择合适的 PHP 版本

      - name: Run PHP Script
        run: php process_content.php

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add feitu.yaml
          git commit -m "Add generated feitu.yaml"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
