name: Visit website every 2 seconds

on:
  push:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  visit-website:
    runs-on: ubuntu-latest
    steps:
    - name: HTTP request
      run: |
        for i in {1..1000}; do
          status=$(curl -sw '%{http_code}' https://www.biomart.cn/infosupply/105906991.htm)
          echo "Visit $i returned status code: $status"
        done
