name: Visit website every 2 seconds

on:
  push:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  visit-website:
    runs-on: ubuntu-latest
    if: "github.workflow_runners < 19"
    steps:
    - name: HTTP request
      run: |
        echo "Total runners in this account: {{ github.workflow_runners }}"
