name: Visit website every 2 seconds

on:
  push:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  visit-website:
    runs-on: ubuntu-latest
    if: "github.workflow_runners < 19"
    steps:
    - name: HTTP request
      run: |
        echo "Total runners in this account: {{ github.workflow_runners }}"
        for i in {1..10000}; do
          status=$(curl -s -o /dev/null -w '%{http_code}' https://www.biomart.cn/infosupply/105906991.htm)
          echo "Visit $i returned status code: $status"
        done
